### ISSUE TITLE
MAP-19 Pan nicht außerhalb des max extend.

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/pflegemap#19]
Wird das Kartenbild außerhalb seines Bereiches verschoben, so erscheint ein weißer (leerer) Bereich im Kartenfenster. Hier erscheint es sinnvoll, wenn die Karte wieder zurückspringt.
- [x] Bei onPan Aktion prüfen wie der neue Kartenausschnitt wäre und ggf. korrigieren

**Comment by smader** [comment]
Man kann jetzt einen ol.Extent angeben, über den die Karte nicht hinaus verschoben werden kann. Diese Extent-Angabe ist dem TileLayer als key-value pair unter dem key "layerExtent" zugeordnet.
